name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2.3"
          - "3.3.0"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install bundler
        run: gem install bundler:$(bundle --version | cut -d' ' -f3-)
      - name: Install deps
        run: bin/rake spec:deps
      - name: Run default task
        run: bin/rake
